### ISSUE TITLE
Unable to import module 'handler'

### ISSUE THREAD

**Issue by rgillen** [lambci/node-custom-lambda#10]
Trying to integrate your library with Lambda-API (https://github.com/jeremydaly/lambda-api)

- I have a simple example working using each library independently.

- However it seems including this line at the top of my `handler.js` causes an error. `const api = require('lambda-api')`

- 'requiring' another library such as 'axios' works fine. So it doesn't seem to be a global problem.

- switching to the built-in 8.10 runtime causes the issue to go away

Unable to import module 'handler'","stackTrace":["    at getHandler (/opt/bootstrap.js:139:13)","    at start (/opt/bootstrap.js:24:15)","    at Object.<anonymous> (/opt/bootstrap.js:19:1)","    at Module._compile (internal/modules/cjs/loader.js:799:30)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)","    at Module.load (internal/modules/cjs/loader.js:666:32)","    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)","    at Function.Module._load (internal/modules/cjs/loader.js:598:3)","    at Function.Module.runMain (internal/modules/cjs/loader.js:862:12)","    at internal/main/run_main_module.js:21:11"]}
Thu Mar 21 22:13:44 UTC 2019 : Lambda execution failed with status 200 due to customer function error: Unable to import module 'handler'. Lambda request id: 3d6a100b-dd7d-4d03-9be8-7e30233d2e8e
Thu Mar 21 22:13:44 UTC 2019 : Method completed with status: 502

## serverless.yml

service: node112

provider:
  name: aws
  runtime: provided
  region: us-west-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
    layers:
      - arn:aws:lambda:us-west-1:553035198032:layer:nodejs11:11

## handler.js

`const api = require('lambda-api')`
`exports.hello = async (event, context) => {`
 `console.log(`Hi from Node.js ${process.version} on Lambda!`)`
 ` return {`
   ` statusCode: 200,`
   `body: JSON.stringify({ message: `Hi from Node.js ${process.version} on Lambda!` })`
  `} `
`}`

**Comment by mhart** [comment]
I suspect because it's looking for the `aws-sdk`, which isn't included with this runtime – try installing `aws-sdk`. That should really be marked as a peer dependency of `lambda-api` in npm IMO.

**Comment by rgillen** [comment]
Thanks... that was it!
