### ISSUE TITLE
Add support for Runtime layer node 6.10

### ISSUE THREAD

**Issue by Vadorequest** [lambci/node-custom-lambda#12]
It may sound silly, but as AWS is officially removing their official node 6.10 runtime, lots of apps developed using node 6.10 won't be deployable by the end of April 2019, and won't be updatable by the end of May 2019.

Due to AWS slow release cycle before Runtime layers were a thing, I believe lots of apps may be in this situation and can't be migrated as fast as they should be.

I personally am in such situation, where I developed an app using node 6 because node 8 wasn't available back then, and can't migrate it as fast as I would like. So, I'm very much interested by a node 6.10 version that behaves like the official AWS runtime, so I can buy a few more months before migrating to a newer node.js runtime.

Please let me know if that's something you'd be interested in doing, if not I'll do it myself (but I'd prefer to keep all the versions in this repo as it seems to acts like a node.js runtime layers HUB) :)

**Comment by mhart** [comment]
Interesting suggestion, but no, I don't think I want to maintain older Node.js versions here – happy to link to your repo in the README if you set one up though!

**Comment by Vadorequest** [comment]
Technically, node 6 is still maintained though, EOL isn't there yet ;)
I don't think there is any maintenance to do for those versions, node 6.10
is the only node version aws allowed and hasn't changed in quite some time.

**Comment by jverneuer** [comment]
I think it might be interesting for certain usecases. I mean even big slow cooperates are using lambda right?
But as fast as node is moving I would rather spend time on making that small adjustments (if any) to keep up than fixing the status quo.
Your legacy is just growing dude.

**Comment by Vadorequest** [comment]
If it was simple I'd have done already. The complexity comes from the many dependencies that do not work on node 8, or did not the last time I tried. I spent days trying and failed.

I don't care about legacy in this case, it is planned to rebuild the product from scratch in the following months, just not that fast. :)

**Comment by Vadorequest** [comment]
@mhart I released a runtime for node v6.10.3, but I'm not sure it works properly and I wonder if you could try it on existing app to let me know if it fails on your side too.

ARN: `arn:aws:lambda:eu-west-1:035907498810:layer:node-6-10-3-runtime:1`

Source code: https://github.com/UnlyEd/aws-lambda-node-runtime-v6.10.3

Here is the issue I encountered, what's weird is that the native AWS runtime works correctly with the same source code, so I assume something that's done by my runtime makes it fail, but I'm not familiar enough with this to know how to debug efficiently.
https://github.com/janaz/aws-lambda-node-runtime/issues/4

If you could try it and let me know how it behaves for you, it would help me very much!
