### ISSUE TITLE
Repository size

### ISSUE THREAD

**Issue by 3r1co** [lambci/node-custom-lambda#21]
Hey,
thanks a lot already for this nice example, but I saw that the repository is very big (more than 300MB). 
Is it really necessary to push the layer.zip in the repository?

**Comment by mhart** [comment]
It's useful for ppl to have to download – is there some reason the repo size is an issue? You can use `git clone --depth 1` if you don't need the full history.

**Comment by 3r1co** [comment]
Ok, thank you. No it's not an issue, I was just asking myself for the reason why this ZIP was there. I'll do the clone with --depth 1. Thanks again!
