### ISSUE TITLE
Multi_line_start_pattern

### ISSUE THREAD

**Issue by Brownie79** [lambci/node-custom-lambda#22]
One of the big differences between the official runtimes and this one is the logs on cloudwatch are not grouped per console.log() message (each /n is split into it's own log line). This makes stack traces very difficult to parse

As per this thread, this can be changed by changing the Agent file for Cloudwatch with the runtime: https://forums.aws.amazon.com/thread.jspa?threadID=158643 to use multi_line_start_pattern 

Would this be something that can be included in this run time? Or if it's out of scope, can someone help figure out how I could add it myself for my own custom runtime?

**Comment by mhart** [comment]
I'm having a bit of trouble parsing what you actually need/want here. The official runtimes convert newlines into `\r` characters – which I'm not a fan of (it's potentially destructive). This runtime, on the other hand, does not override `console.log`.

If you want to bring your own logging framework, you can output logs however you'd like

**Comment by Brownie79** [comment]
So, from what I understood in the previously linked thread, you can set the runtime to group logs by date-time instead of overwriting with \r ?

Basically when I check logs in Cloudwatch, I would like all logs from 1 console.log() written together so it maintains tabbing and spacing. Right now, when it logs, all the logs get left shifted and treated as new lines and lose context 
An example of my log file: 
These are only two console.log() statements, but they are printed as 13 different lines. 
![image](https://user-images.githubusercontent.com/3674978/68423939-d8d76a00-0157-11ea-8f86-6086d771800f.png)

I don't think you need to change the way logs work or edit them in any way, but change the cloudwatch config to group them by date-time (I think). But I can't figure out where the config for cloudwatch is in the runtime

**Comment by mhart** [comment]
There's no Cloudwatch config in the runtime – the Lambda parent system handles that. It forwards any output from custom runtimes to Cloudwatch. So there's no way to configure the way Cloudwatch will treat it. The only thing you can control is how you format things when you console.log (or process.stdout.write) them

**Comment by Brownie79** [comment]
Ah, so maybe the thread is only applicable for if you're manually creating and building Cloud Watch logging for ec2 instances. 

Thanks for your help
