### ISSUE TITLE
node 13 custom runtime

### ISSUE THREAD

**Issue by giorgio-zamparelli** [lambci/node-custom-lambda#23]
Hi there,
I would like to use a custom runtime with node 13 to try out the unflagged implementation of ES modules available from node 13.

Is there any plan to release a custom runtime for node 13 as part of this project?

**Comment by mhart** [comment]
There are no plans, no. Node.js 13 isn't a long-term release – that will be Node 14, which I definitely have plans to release a custom runtime for 👍

**Comment by giorgio-zamparelli** [comment]
yes but ES modules are available currently unflagged only on node 13 so
node 13 has a great potential right now.
Also AWS started releasing the LTS very early after their official release.
The runtime nodejs12.x was released the 19 of November just 3 weeks after
node 12 became LTS.
So essentially now there is very little value added in creating custom
runtime for LTS versions of node since AWS releases the official runtime
just weeks after.
I think there is a lot of space and value to be created from a custom
runtime for non LTS node versions like node 13.
