### ISSUE TITLE
`callback` handler signature is not supported

### ISSUE THREAD

**Issue by TooTallNate** [lambci/node-custom-lambda#5]
It appears that you can only use `return` to return values from a handler function. Callback signature could easily be supported without any additional dependencies via [`util.promisify()`](https://nodejs.org/api/util.html#util_util_promisify_original). Would you be interested in a PR?

**Comment by mhart** [comment]
Kinda wanted to keep things simple tbh. Is this because you have an existing Lambda that uses the callback signature?

**Comment by TooTallNate** [comment]
Indeed.

At the very least, it took some time to debug what was happening, so perhaps a handler arity check on `handler.length` and reject the initialization if it's `=== 3` with an explicit message would be helpful (though I think that would be _more_ code than calling `util.promisify()`).

**Comment by TooTallNate** [comment]
This is the patch FWIW:

```diff
@@ -3,6 +3,7 @@
  */

 const http = require('http');
+const { promisify } = require('util');

 const RUNTIME_PATH = '/2018-06-01/runtime';

@@ -152,7 +153,7 @@ function getHandler() {
                throw new Error(`Handler '${handlerName}' from '${modulePath}' is not a function`);
        }

-       return userHandler;
+       return userHandler.length >= 3 ? promisify(userHandler) : userHandler;
 }

 async function request(options) {
```

**Comment by ttonyh** [comment]
I tested the patch that @TooTallNate posted and it works great! Please consider adding it for backward compatibility with existing Lambda functions.

**Comment by mhart** [comment]
Thanks for this – sorry it took me a while to get to.

This is now supported in the latest versions 🎉
