### ISSUE TITLE
`context.succeed` is not a function

### ISSUE THREAD

**Issue by DanWard** [lambci/node-custom-lambda#8]
Hi there,

I'm using https://github.com/awslabs/aws-serverless-express as a wrapper for my Express application in Lambda. Which fails with the below error. It seems to be looking for `context.succeed` which exists on the standard AWS nodejs environment but none of the custom ones. 
I've also attached the test code, and the outputs for context in both environments.
I'm not sure what course of action you would like to proceed with, but it could stop people from deploying using the layer in the future.

Thanks!
Daniel

Crash log:
> /var/task/node_modules/aws-serverless-express/src/index.js:243
> if (params.resolutionMode === 'CONTEXT_SUCCEED') return params.context.succeed(params2.response)
> ^
> 
> TypeError: params.context.succeed is not a function
> at Object.succeed (/var/task/node_modules/aws-serverless-express/src/index.js:243:78)
> at IncomingMessage.response.on.on (/var/task/node_modules/aws-serverless-express/src/index.js:105:16)
> at IncomingMessage.emit (events.js:202:15)
> at IncomingMessage.EventEmitter.emit (domain.js:439:20)
> at endReadableNT (_stream_readable.js:1129:12)
> at processTicksAndRejections (internal/process/next_tick.js:76:17)

Test code:
```
exports.handler = async(event, context) => {
  console.log(event, context);
}
```

Node 10/11 (output is the same)
> START RequestId: c99f7d98-af85-4860-90a4-5433bfc65d91 Version: $LATEST
> { key1: 'value1', key2: 'value2', key3: 'value3' } { awsRequestId: 'c99f7d98-af85-4860-90a4-5433bfc65d91',
>   invokedFunctionArn:
>    'arn:aws:lambda:ap-southeast-1:795327357717:function:Example',
>   logGroupName: '/aws/lambda/Example',
>   logStreamName: '2019/02/06/[$LATEST]6da0c26641034929843fb503163be206',
>   functionName: 'Example',
>   functionVersion: '$LATEST',
>   memoryLimitInMB: '128',
>   getRemainingTimeInMillis: [Function: getRemainingTimeInMillis] }
> END RequestId: c99f7d98-af85-4860-90a4-5433bfc65d91
> REPORT RequestId: c99f7d98-af85-4860-90a4-5433bfc65d91	Duration: 255.44 ms	Billed Duration: 300 ms 	Memory Size: 128 MB	Max Memory Used: 55 MB

Node 8.10 from AWS
> START RequestId: ffa39ca7-7d64-4879-8af1-d9f1457f6540 Version: $LATEST
> 2019-02-06T09:12:29.175Z	ffa39ca7-7d64-4879-8af1-d9f1457f6540	{ key1: 'value1', key2: 'value2', key3: 'value3' } { callbackWaitsForEmptyEventLoop: [Getter/Setter],
>   done: [Function: done],
>   succeed: [Function: succeed],
>   fail: [Function: fail],
>   logGroupName: '/aws/lambda/Example',
>   logStreamName: '2019/02/06/[$LATEST]84f0d049f76d4e6a9e010ea66b07d9d0',
>   functionName: 'Example',
>   memoryLimitInMB: '128',
>   functionVersion: '$LATEST',
>   getRemainingTimeInMillis: [Function: getRemainingTimeInMillis],
>   invokeid: 'ffa39ca7-7d64-4879-8af1-d9f1457f6540',
>   awsRequestId: 'ffa39ca7-7d64-4879-8af1-d9f1457f6540',
>   invokedFunctionArn: 'arn:aws:lambda:ap-southeast-1:795327357717:function:Example' }
> END RequestId: ffa39ca7-7d64-4879-8af1-d9f1457f6540
> REPORT RequestId: ffa39ca7-7d64-4879-8af1-d9f1457f6540	Duration: 66.89 ms	Billed Duration: 100 ms 	Memory Size: 128 MB	Max Memory Used: 20 MB

**Comment by mhart** [comment]
`context.succeed` is a legacy function from the original Node.js v0.10 runtime that AWS created – it's no longer documented: https://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-context.html

Is there a reason you're using this instead of returning a Promise or calling the callback?

**Comment by mhart** [comment]
I believe the `proxy` function in aws-serverless-express takes an argument, `resolutionMode`:

https://github.com/awslabs/aws-serverless-express/blob/86c0c58009f26b57f319d9d5089fd1a1cf86ce06/src/index.js#L197-L199

If you set that to `'PROMISE'` it should work: https://github.com/awslabs/aws-serverless-express/blob/86c0c58009f26b57f319d9d5089fd1a1cf86ce06/src/index.js#L243-L245

**Comment by DanWard** [comment]
> I believe the `proxy` function in aws-serverless-express takes an argument, `resolutionMode`:
> 
> https://github.com/awslabs/aws-serverless-express/blob/86c0c58009f26b57f319d9d5089fd1a1cf86ce06/src/index.js#L197-L199
> 
> If you set that to `'PROMISE'` it should work: https://github.com/awslabs/aws-serverless-express/blob/86c0c58009f26b57f319d9d5089fd1a1cf86ce06/src/index.js#L243-L245

Thanks for the help. I took what you suggested and did some more digging. I found that you have to run it like this:

```
exports.handler = async (event, context) => awsServerlessExpress.proxy(server, event, context, 'PROMISE').promise;
```
As per this issue ticket - https://github.com/awslabs/aws-serverless-express/issues/134.

Thanks once again!

**Comment by mclark-newvistas** [comment]
Please document this! I didn't expect to find a resolution in closed issues.
